# Generated by Django 3.2.13 on 2022-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_ID',
            field=models.PositiveIntegerField(verbose_name='Vehicle ID'),
        ),
    ]
