# Generated by Django 3.2.13 on 2022-05-10 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
    ]
