# Generated by Django 3.2.13 on 2022-05-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
