# Generated by Django 3.2.13 on 2022-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas')], max_length=20, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer',
            field=models.CharField(choices=[('miles', 'Miles'), ('kilometers', 'Kilometers')], max_length=20, verbose_name='Odometer'),
        ),
    ]
