# Generated by Django 3.2.13 on 2022-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20220606_0709'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['id'], name='vehicle_veh_id_f58f07_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['carrier'], name='vehicle_veh_carrier_33a750_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['active'], name='vehicle_veh_active_f2327e_idx'),
        ),
    ]
