# Generated by Django 3.2.13 on 2022-08-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20220810_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
