# Generated by Django 3.2.13 on 2022-06-08 09:26

from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=2000)),
                ('refresh_token', models.CharField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.CharField(blank=True, max_length=300, null=True)),
                ('external_load_id', models.CharField(blank=True, max_length=300, null=True)),
                ('age', models.CharField(blank=True, max_length=300, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('computed_miledge', models.CharField(blank=True, max_length=300, null=True)),
                ('miledge', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_state', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_geolocation_latitude', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_geolocation_longitude', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_deadhead', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_state', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_geolocation_latitude', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_geolocation_longitude', models.CharField(blank=True, max_length=300, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=300, null=True)),
                ('pickup_date_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_date_time_utc', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=300, null=True)),
                ('amount_type', models.CharField(blank=True, max_length=100, null=True)),
                ('load_size', models.CharField(blank=True, max_length=300, null=True)),
                ('load_length', models.CharField(blank=True, max_length=300, null=True)),
                ('load_weight', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_stops', models.IntegerField(blank=True, null=True)),
                ('team_driving', models.BooleanField(blank=True, default=False, null=True)),
                ('load_status', models.CharField(blank=True, max_length=100, null=True)),
                ('poster_id', models.CharField(blank=True, max_length=300, null=True)),
                ('poster_name', models.CharField(blank=True, max_length=300, null=True)),
                ('poster_phone', models.CharField(blank=True, max_length=300, null=True)),
                ('poster_mcnumber', models.CharField(blank=True, max_length=300, null=True)),
                ('poster_dotnumber', models.CharField(blank=True, max_length=300, null=True)),
                ('is_ocfp', models.BooleanField(blank=True, null=True)),
                ('metadata', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
