# Generated by Django 3.2.13 on 2022-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='source',
            field=models.CharField(blank=True, default='123LoadBoard', max_length=300, null=True),
        ),
    ]
