# Generated by Django 3.2.13 on 2022-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_loads_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='nauvus_estimate',
            field=models.CharField(blank=True, default='0.00', max_length=300, null=True),
        ),
    ]
