# Generated by Django 3.2.13 on 2022-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0003_loads_nauvus_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='total_amount',
            field=models.CharField(blank=True, default='0.00', max_length=300, null=True),
        ),
    ]
