# Generated by Django 3.2.13 on 2022-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loads", "0004_loads_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loads",
            name="total_amount",
            field=models.FloatField(
                blank=True, default=0.0, max_length=300, null=True
            ),
        ),
    ]
