# Generated by Django 3.2.13 on 2022-08-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0005_alter_loads_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='load_weight_in_lbs',
            field=models.CharField(blank=True, default='0', max_length=300, null=True),
        ),
    ]
