# Generated by Django 3.2.13 on 2022-11-30 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_auto_20220810_1127'),
        ('dispatcher', '0028_auto_20220810_1127'),
        ('driver', '0016_merge_20220930_0438'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loads', '0006_loads_load_weight_in_lbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('destination', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('dropoff_date', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('available', 'AVAILABLE'), ('booked', 'BOOKED'), ('pending', 'PENDING'), ('upcoming', 'UPCOMING'), ('underway', 'UNDERWAY'), ('delivered', 'DELIVERED'), ('partial_settled', 'PARTIAL_SETTLED'), ('completed', 'COMPLETED')], default='', max_length=50)),
                ('details', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('contact', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('posted_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='broker.broker')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dispatcher.dispatcheruser')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='driver.driver')),
            ],
            options={
                'db_table': 'loads',
            },
        ),
        migrations.CreateModel(
            name='LoadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True, unique=True)),
            ],
            options={
                'db_table': 'load_source',
            },
        ),
        migrations.CreateModel(
            name='LoadStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('load_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loads.load')),
            ],
            options={
                'db_table': 'load_status_history',
            },
        ),
        migrations.DeleteModel(
            name='Loads',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='expires',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='loadboard_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterModelTable(
            name='accesstoken',
            table='access_tokens',
        ),
        migrations.AddField(
            model_name='load',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loads.loadsource'),
        ),
    ]
