# Generated by Django 3.2.13 on 2022-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0007_auto_20221130_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadsource',
            name='description',
        ),
        migrations.AddField(
            model_name='loadsource',
            name='load_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loadsource',
            name='source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
