# Generated by Django 3.2.13 on 2022-12-02 18:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0008_auto_20221130_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='origin',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
