# Generated by Django 3.2.13 on 2022-12-12 18:02

from django.db import migrations, models
import nauvus.apps.loads.models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0010_auto_20221202_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='rc_document',
            field=models.FileField(blank=True, null=True, upload_to=nauvus.apps.loads.models.upload_to, validators=[nauvus.apps.loads.models.validate_document_file], verbose_name='Rate Confirmation Document'),
        ),
    ]
