# Generated by Django 3.2.13 on 2022-12-19 18:54

from django.db import migrations, models
import django.db.models.deletion
import nauvus.apps.loads.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0011_load_rc_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteDeliveryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=nauvus.apps.loads.models.upload_complete_delivery_documents_to, validators=[nauvus.apps.loads.models.validate_document_file])),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('load_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loads.load')),
            ],
            options={
                'db_table': 'complete_delivery_documents',
            },
        ),
    ]
