# Generated by Django 3.2.13 on 2022-12-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0012_completedeliverydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='final_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
