# Generated by Django 3.2.13 on 2022-12-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0014_load_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='delivery_date',
        ),
    ]
