# Generated by Django 3.2.13 on 2023-01-04 17:53

from django.db import migrations, models
import nauvus.apps.loads.models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0015_remove_load_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedeliverydocument',
            name='document',
            field=models.FileField(null=True, upload_to=nauvus.apps.loads.models.upload_complete_delivery_documents_to, validators=[nauvus.apps.loads.models.validate_document_file]),
        ),
    ]
