# Generated by Django 3.2.13 on 2023-01-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0016_alter_completedeliverydocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedeliverydocument',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
