# Generated by Django 3.2.13 on 2023-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0017_alter_completedeliverydocument_delivered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedeliverydocument',
            name='delivered_date',
        ),
        migrations.AddField(
            model_name='load',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
