# Generated by Django 3.2.13 on 2023-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0018_auto_20230111_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedeliverydocument',
            name='document_type',
            field=models.CharField(choices=[('bill_of_lading', 'BILL_OF_LADING'), ('lumper_receipt', 'LUMPER_RECEIPT'), ('other', 'OTHER')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='completedeliverydocument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
