# Generated by Django 3.2.13 on 2023-01-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0019_auto_20230113_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompleteDeliveryDocument',
            new_name='DeliveryDocument',
        ),
        migrations.AlterModelTable(
            name='deliverydocument',
            table='delivery_documents',
        ),
    ]
