# Generated by Django 3.2.13 on 2023-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0021_auto_20230126_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='reference_title',
            field=models.CharField(default='Load without Ref', max_length=100),
        ),
    ]
