# Generated by Django 3.2.13 on 2023-02-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0022_alter_load_reference_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='load',
            name='destination',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='load',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='load',
            name='origin',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
