# Generated by Django 3.2.13 on 2023-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0023_auto_20230207_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='invoice_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
