# Generated by Django 3.2.13 on 2023-02-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0031_carrier_invoice_email'),
        ('loads', '0024_load_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carrier.carrier'),
        ),
    ]
