# Generated by Django 3.2.13 on 2023-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0025_load_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
