# Generated by Django 3.2.13 on 2023-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0026_load_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='current_status',
            field=models.CharField(blank=True, choices=[('available', 'AVAILABLE'), ('booked', 'BOOKED'), ('pending', 'PENDING'), ('upcoming', 'UPCOMING'), ('underway', 'UNDERWAY'), ('delivered', 'DELIVERED'), ('partial_settled', 'PARTIAL_SETTLED'), ('completed', 'COMPLETED'), ('draft', 'DRAFT')], default='', max_length=50),
        ),
    ]
