version: 0.0
os: linux
files:
  - source: /
    destination: /home/projects/nauvus-backend
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/projects/nauvus-backend
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: deployment/scripts/deploy.sh
      timeout: 6000
      runas: root

      