# Generated by Django 3.2.13 on 2022-06-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_broker'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Load',
            new_name='LoadItem',
        ),
    ]
