# Generated by Django 3.2.13 on 2022-06-10 11:35

from django.db import migrations, models
import django.db.models.deletion
import nauvus.apps.bookings.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20220609_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookload',
            name='is_booked_by_dispatcher',
            field=models.BooleanField(default=True, verbose_name='Is Booked By Dispatcher'),
        ),
        migrations.CreateModel(
            name='BookLoadDeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to=nauvus.apps.bookings.models.wrapper_proof, verbose_name='Proof')),
                ('book_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
