# Generated by Django 3.2.13 on 2022-06-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_auto_20220610_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.CharField(blank=True, max_length=300, null=True)),
                ('external_load_id', models.CharField(blank=True, max_length=300, null=True)),
                ('age', models.CharField(blank=True, max_length=300, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=300, null=True)),
                ('received_at', models.CharField(blank=True, max_length=300, null=True)),
                ('computed_miledge', models.CharField(blank=True, max_length=300, null=True)),
                ('miledge', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_state', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_geolocation_latitude', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_geolocation_longitude', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_deadhead', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_state', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_geolocation_latitude', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_geolocation_longitude', models.CharField(blank=True, max_length=300, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=300, null=True)),
                ('pickup_date_time', models.CharField(blank=True, max_length=300, null=True)),
                ('pickup_date_time_utc', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.CharField(blank=True, max_length=300, null=True)),
                ('amount_type', models.CharField(blank=True, max_length=100, null=True)),
                ('load_size', models.CharField(blank=True, max_length=300, null=True)),
                ('load_length', models.CharField(blank=True, max_length=300, null=True)),
                ('load_weight', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_stops', models.IntegerField(blank=True, null=True)),
                ('team_driving', models.BooleanField(blank=True, default=False, null=True)),
                ('load_status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_ocfp', models.BooleanField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_favourite', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
