# Generated by Django 3.2.13 on 2022-06-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_favouriteload'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteload',
            name='pickup_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='loaditem',
            name='pickup_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
