# Generated by Django 3.2.13 on 2022-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20220613_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookload',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=100, verbose_name='Status'),
        ),
    ]
