# Generated by Django 3.2.13 on 2022-06-15 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0026_merge_20220614_0919'),
        ('bookings', '0007_alter_bookload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookload',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher.dispatcher'),
        ),
    ]
