# Generated by Django 3.2.13 on 2022-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_externalload'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalload',
            name='is_book_by_dispatcher',
            field=models.BooleanField(default=False, verbose_name='Dispatcher add external load'),
        ),
    ]
