# Generated by Django 3.2.13 on 2022-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_externalload_is_book_by_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalload',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=100, verbose_name='Status'),
        ),
    ]
