# Generated by Django 3.2.13 on 2022-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_externalload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalload',
            name='dropoff',
        ),
        migrations.RemoveField(
            model_name='externalload',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='externalload',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='externalload',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='externalload',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='externalload',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_additional_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='additional notes of the dropoff point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_address_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Dropoff Point City'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_address_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Dropoff Point state'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_address_zipcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Dropoff Point zipcode'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contact name of dropoff point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='email of the dropoff point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='dropoff number of the of the dropoff point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='dropoff_phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='phone number  of dropoff point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_additional_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='additional notes of the pickup point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_address_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Pickup Point City'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_address_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Pickup Point state'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_address_zipcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pickup Point zipcode'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='pickup point contact name'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='email of the of the pickup point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='pickup number of the of the pickup point'),
        ),
        migrations.AddField(
            model_name='externalload',
            name='pickup_phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='phone number of the pickup point'),
        ),
        migrations.AlterField(
            model_name='externalload',
            name='rc_document',
            field=models.FileField(blank=True, null=True, upload_to='booking/rc_document', verbose_name='Rc Document of the Load'),
        ),
    ]
