# Generated by Django 3.2.13 on 2022-06-23 06:54

from django.db import migrations, models
import nauvus.apps.bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20220620_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloaddeliveryproof',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to=nauvus.apps.bookings.models.wrapper_signature, verbose_name='Signature'),
        ),
    ]
