# Generated by Django 3.2.13 on 2022-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookloaddeliveryproof_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaditem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
