# Generated by Django 3.2.13 on 2022-07-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_brokerplatform_image'),
        ('bookings', '0013_bookloaddeliveryproof_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaditem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='broker.brokerplatform'),
        ),
    ]
