# Generated by Django 3.2.13 on 2022-07-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_loaditem_price'),
        ('bookings', '0014_loaditem_source'),
    ]

    operations = [
    ]
