# Generated by Django 3.2.13 on 2022-07-21 07:00

from django.db import migrations, models
import nauvus.apps.bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_loaditem_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookload',
            name='rate_confirmation_document',
            field=models.FileField(blank=True, null=True, upload_to=nauvus.apps.bookings.models.wrapper_rate_confirmation_document, verbose_name='Rate Confirmation'),
        ),
    ]
