# Generated by Django 3.2.13 on 2022-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_loaditem_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaditem',
            name='pickup_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loaditem',
            name='pickup_date_time_utc',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
