# Generated by Django 3.2.13 on 2022-07-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_merge_0014_loaditem_price_0014_loaditem_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookload',
            name='book_by',
            field=models.CharField(blank=True, choices=[('dispatcher', 'Dispatcher'), ('carrier', 'Carrier'), ('driver', 'driver')], max_length=100, null=True, verbose_name='Booking Choice'),
        ),
        migrations.AlterField(
            model_name='bookload',
            name='is_booked_by_dispatcher',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Booked By Dispatcher'),
        ),
    ]
