# Generated by Django 3.2.13 on 2022-07-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20220720_0447'),
        ('bookings', '0016_bookload_final_price'),
    ]

    operations = [
    ]
