# Generated by Django 3.2.13 on 2022-08-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20220810_1127'),
        ('bookings', '0016_bookload_final_price'),
    ]

    operations = [
    ]
