# Generated by Django 3.2.13 on 2022-07-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_merge_20220726_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookload',
            name='is_booked_by_dispatcher',
        ),
    ]
