# Generated by Django 3.2.13 on 2022-08-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_merge_20220815_1210'),
        ('bookings', '0018_remove_bookload_is_booked_by_dispatcher'),
    ]

    operations = [
    ]
