# Generated by Django 3.2.13 on 2022-08-29 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_merge_20220827_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookload',
            name='book_by',
            field=models.CharField(blank=True, choices=[('dispatcher', 'Dispatcher'), ('carrier', 'Carrier'), ('driver', 'Driver')], max_length=100, null=True, verbose_name='Booking Choice'),
        ),
        migrations.CreateModel(
            name='BookLoadLiveShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('book_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
