# Generated by Django 3.2.13 on 2022-09-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_merge_20220816_0610'),
        ('bookings', '0021_bookloadnotes'),
    ]

    operations = [
    ]
