# Generated by Django 3.2.13 on 2022-06-09 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_rename_broker_brokerplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_broker_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='Load Broker ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='phone')),
                ('mc_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='MC Number')),
                ('dot_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='DOT Number')),
                ('metadata', models.JSONField(verbose_name='Metadata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
