# Generated by Django 3.2.13 on 2022-07-19 08:23

from django.db import migrations, models
import nauvus.apps.broker.models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerplatform',
            name='image',
            field=models.ImageField(default='', upload_to=nauvus.apps.broker.models.wrapper_source_image, verbose_name='Source Image'),
        ),
    ]
