# Generated by Django 3.2.13 on 2022-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_brokerplatform_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brokerplatform',
            index=models.Index(fields=['id'], name='broker_brok_id_b07eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerplatform',
            index=models.Index(fields=['name'], name='broker_brok_name_4c75d2_idx'),
        ),
    ]
