# Generated by Django 3.2.13 on 2022-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_auto_20220810_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='broker',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='contact first name'),
        ),
        migrations.AddField(
            model_name='broker',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='contact last name'),
        ),
        migrations.AddField(
            model_name='broker',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='broker',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='broker',
            name='street1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street1 Address'),
        ),
        migrations.AddField(
            model_name='broker',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street2 Address'),
        ),
        migrations.AddField(
            model_name='broker',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip'),
        ),
    ]
