# Generated by Django 3.2.13 on 2022-12-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_auto_20221219_1517'),
        ('broker', '0008_alter_broker_metadata'),
    ]

    operations = [
    ]
