# Generated by Django 3.2.13 on 2022-12-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_merge_20221220_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='mc_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='MC Number'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='metadata',
            field=models.JSONField(verbose_name='Metadata'),
        ),
    ]
