# Generated by Django 3.2.13 on 2022-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_auto_20221220_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
    ]
