# Generated by Django 3.2.13 on 2022-05-10 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
    ]
