# Generated by Django 3.2.13 on 2022-05-10 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220510_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=20, verbose_name='Email ')),
                ('otp', models.CharField(max_length=10, verbose_name='OTP')),
                ('verified', models.BooleanField(default=False)),
                ('reset_process_id', models.UUIDField(default=uuid.uuid4, verbose_name='Uuid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
