# Generated by Django 3.2.13 on 2022-05-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220511_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('dispatcher', 'Dispatcher'), ('carrier_owner', 'Carrier Admin'), ('carrier_admin_operator', 'Carrier Admin Operator'), ('nauvus_backroom_staff', 'Nauvus Backroom Staff'), ('nauvus_administrator', 'Nauvus Administrator'), ('driver', 'Driver')], max_length=30, verbose_name='User Type'),
        ),
    ]
