# Generated by Django 3.2.13 on 2022-06-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailupdateotpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOtpVerification',
        ),
        migrations.AddField(
            model_name='user',
            name='email_reset_key',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
