# Generated by Django 3.2.13 on 2022-08-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220810_1127'),
        ('users', '0010_user_stripe_customer_id'),
    ]

    operations = [
    ]
