# Generated by Django 3.2.13 on 2022-12-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailupdateotpverification',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email '),
        ),
    ]
