# Generated by Django 3.2.13 on 2022-05-05 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('source', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Email', 'Email'), ('Blog', 'Blog'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Source')),
                ('no_of_trucks', models.PositiveIntegerField(default=0, help_text='How many vehicles Do you plan for Nauvus?')),
                ('no_of_trailers', models.PositiveIntegerField(default=0, help_text='How many trailers Do you plan for Nauvus?')),
                ('factoring_company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Factoring Company')),
                ('gross_weekly_revenue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gross Weekly Revenue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarrierW9Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('w9_document', models.FileField(upload_to='', verbose_name='W-9 Document')),
                ('taxpayer_ID_number', models.PositiveIntegerField()),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarrierTrailerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer_type', models.CharField(blank=True, choices=[('Dry Van', 'Dry Van'), ('Reefer', 'Reefer'), ('Flatbed', 'Flatbed'), ('Step Deck', 'Step Deck'), ('Box Truck', 'Box Truck'), ('Hotshot', 'Hotshot'), ('Power Only', 'Power Only'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Trailer Type')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarrierTrailerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer_size', models.CharField(blank=True, choices=[('48 Feet', '48 Feet'), ('40 Feet', '40 Feet'), ('45 Feet', '45 Feet'), ('53 Feet', '53 Feet'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Trailer Size')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarrierFleetApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operating_authority_letter', models.FileField(upload_to='', verbose_name='Authority Letter')),
                ('insurance_certificate', models.FileField(upload_to='', verbose_name='Insurance Certificate')),
                ('business_documentation', models.FileField(upload_to='', verbose_name='Business Documentation')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarrierBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
