# Generated by Django 3.2.13 on 2022-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierw9information',
            name='taxpayer_ID_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxpayer ID'),
        ),
    ]
