# Generated by Django 3.2.13 on 2022-05-10 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0003_auto_20220505_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='carrierbroker',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='carrierfleetapplication',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='carriertrailersize',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='carriertrailertype',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='carrierw9information',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
    ]
