# Generated by Django 3.2.13 on 2022-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0004_auto_20220510_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='business_documentation',
            field=models.FileField(upload_to='carrier/fleet-application/business-documentation', verbose_name='Business Documentation'),
        ),
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='insurance_certificate',
            field=models.FileField(upload_to='carrier/fleet-application/insurance-certificate', verbose_name='Insurance Certificate'),
        ),
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='operating_authority_letter',
            field=models.FileField(upload_to='carrier/fleet-application/operating-authority-letter', verbose_name='Authority Letter'),
        ),
        migrations.AlterField(
            model_name='carrierw9information',
            name='w9_document',
            field=models.FileField(upload_to='carrier/w9-information/business-documentation', verbose_name='W-9 Document'),
        ),
    ]
