# Generated by Django 3.2.13 on 2022-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0005_auto_20220510_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierw9information',
            name='w9_document',
            field=models.FileField(upload_to='carrier/w9-information', verbose_name='W-9 Document'),
        ),
    ]
