# Generated by Django 3.2.13 on 2022-05-11 05:35

from django.db import migrations, models
import nauvus.apps.carrier.models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0007_auto_20220511_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='business_documentation',
            field=models.FileField(upload_to=nauvus.apps.carrier.models.wrapper_business_documentation, verbose_name='Business Documentation'),
        ),
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='insurance_certificate',
            field=models.FileField(upload_to=nauvus.apps.carrier.models.wrapper_insurance_certificate, verbose_name='Insurance Certificate'),
        ),
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='operating_authority_letter',
            field=models.FileField(upload_to=nauvus.apps.carrier.models.wrapper_operating_authority_letter, verbose_name='Authority Letter'),
        ),
        migrations.AlterField(
            model_name='carrierw9information',
            name='w9_document',
            field=models.FileField(upload_to=nauvus.apps.carrier.models.wrapper_w9_info, verbose_name='W-9 Document'),
        ),
    ]
