# Generated by Django 3.2.13 on 2022-05-13 10:15

from django.db import migrations, models
import django.db.models.deletion
import nauvus.apps.carrier.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0008_auto_20220511_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('envelope_id', models.CharField(max_length=255, verbose_name='Carrier Envelope ID')),
                ('is_signed', models.BooleanField()),
                ('document', models.FileField(upload_to=nauvus.apps.carrier.models.wrapper_w9_info, verbose_name='document')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
