# Generated by Django 3.2.13 on 2022-05-13 10:33

from django.db import migrations, models
import nauvus.apps.carrier.models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0009_carrierserviceagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierserviceagreement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=nauvus.apps.carrier.models.wrapper_w9_info, verbose_name='document'),
        ),
    ]
