# Generated by Django 3.2.13 on 2022-05-13 11:06

from django.db import migrations, models
import nauvus.apps.carrier.models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0010_alter_carrierserviceagreement_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierserviceagreement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=nauvus.apps.carrier.models.wrapper_service_agreement_document, verbose_name='document'),
        ),
    ]
