# Generated by Django 3.2.13 on 2022-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0011_alter_carrierserviceagreement_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierserviceagreement',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
