# Generated by Django 3.2.13 on 2022-06-01 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrier', '0012_alter_carrierserviceagreement_is_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='user',
        ),
        migrations.CreateModel(
            name='CarrierUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('access_type', models.CharField(blank=True, choices=[('full_admin', 'Full Admin'), ('redy_only_admin', 'Read Only Admin')], default='redy_only_admin', max_length=20, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
