# Generated by Django 3.2.13 on 2022-06-01 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0013_auto_20220601_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierbroker',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
        migrations.AlterField(
            model_name='carrierserviceagreement',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
        migrations.AlterField(
            model_name='carriertrailersize',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
        migrations.AlterField(
            model_name='carriertrailertype',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
        migrations.AlterField(
            model_name='carrierw9information',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
    ]
