# Generated by Django 3.2.13 on 2022-06-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0014_auto_20220601_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierserviceagreement',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
    ]
