# Generated by Django 3.2.13 on 2022-06-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0015_alter_carrierserviceagreement_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierbroker',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
        migrations.AlterField(
            model_name='carrierfleetapplication',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
        migrations.AlterField(
            model_name='carrierserviceagreement',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
        migrations.AlterField(
            model_name='carriertrailersize',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
        migrations.AlterField(
            model_name='carrierw9information',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
    ]
