# Generated by Django 3.2.13 on 2022-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0017_alter_carriertrailertype_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrieruser',
            name='is_current_organization',
            field=models.BooleanField(default=False, help_text='To find Current Carrier Organization'),
        ),
    ]
