# Generated by Django 3.2.13 on 2022-06-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0020_carrieradmininvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrieradmininvitation',
            name='pending_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
