# Generated by Django 3.2.13 on 2022-06-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0022_auto_20220609_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarrierAdminInvitation',
        ),
    ]
