# Generated by Django 3.2.13 on 2022-06-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0023_delete_carrieradmininvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrieruser',
            name='permission',
        ),
    ]
