# Generated by Django 3.2.13 on 2022-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0024_remove_carrieruser_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='dot_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DOT Number'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='mc_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MC Number'),
        ),
    ]
