# Generated by Django 3.2.13 on 2022-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0025_auto_20220705_0516'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['id'], name='carrier_car_id_27afa1_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierbroker',
            index=models.Index(fields=['id'], name='carrier_car_id_270b46_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierbroker',
            index=models.Index(fields=['carrier'], name='carrier_car_carrier_03034d_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierdispatcher',
            index=models.Index(fields=['id'], name='carrier_car_id_6c1bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierdispatcher',
            index=models.Index(fields=['carrier'], name='carrier_car_carrier_f67a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierdispatcher',
            index=models.Index(fields=['carrier', 'active'], name='carrier_car_carrier_772c57_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierdispatcher',
            index=models.Index(fields=['dispatcher', 'active'], name='carrier_car_dispatc_3cc37f_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierdispatcher',
            index=models.Index(fields=['dispatcher'], name='carrier_car_dispatc_2da041_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierfleetapplication',
            index=models.Index(fields=['carrier'], name='carrier_car_carrier_d1275b_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierserviceagreement',
            index=models.Index(fields=['id'], name='carrier_car_id_be761a_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierserviceagreement',
            index=models.Index(fields=['carrier'], name='carrier_car_carrier_1c1549_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieruser',
            index=models.Index(fields=['user'], name='carrier_car_user_id_ac8dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieruser',
            index=models.Index(fields=['carrier'], name='carrier_car_carrier_3458be_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieruser',
            index=models.Index(fields=['user', 'is_current_organization'], name='carrier_car_user_id_0a8444_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieruser',
            index=models.Index(fields=['carrier', 'is_owner'], name='carrier_car_carrier_e2a808_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieruser',
            index=models.Index(fields=['user', 'access_type'], name='carrier_car_user_id_f6874a_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieruser',
            index=models.Index(fields=['user', 'is_owner'], name='carrier_car_user_id_d4f01b_idx'),
        ),
        migrations.AddIndex(
            model_name='carrieruser',
            index=models.Index(fields=['user', 'carrier'], name='carrier_car_user_id_fbcbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierw9information',
            index=models.Index(fields=['id'], name='carrier_car_id_fa11bc_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierw9information',
            index=models.Index(fields=['carrier'], name='carrier_car_carrier_be9598_idx'),
        ),
    ]
