# Generated by Django 3.2.13 on 2022-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0026_auto_20220810_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='fleet_id',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
