# Generated by Django 3.2.13 on 2022-11-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0013_auto_20221110_0949'),
        ('carrier', '0027_carrier_fleet_id'),
    ]

    operations = [
    ]
