# Generated by Django 3.2.13 on 2022-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0029_auto_20221110_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='street1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street1 Address'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street2 Address'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip'),
        ),
    ]
