# Generated by Django 3.2.13 on 2023-02-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0030_auto_20221219_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
