# Generated by Django 3.2.13 on 2022-06-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('iso3', models.CharField(blank=True, max_length=255, null=True, verbose_name='iso3')),
                ('iso2', models.CharField(blank=True, max_length=255, null=True, verbose_name='iso2')),
                ('numeric_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='numeric_code')),
                ('phone_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone_code')),
                ('capital', models.CharField(blank=True, max_length=255, null=True, verbose_name='capital')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='currency')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='region')),
                ('subregion', models.CharField(blank=True, max_length=255, null=True, verbose_name='subregion')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='id')),
                ('state_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='state_code')),
                ('city_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='city_type')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.state')),
            ],
        ),
    ]
