# Generated by Django 3.2.13 on 2022-06-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='city_type',
            new_name='state_type',
        ),
    ]
