# Generated by Django 3.2.13 on 2022-06-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_rename_city_type_state_state_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='cities_city_name_a4d1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='cities_coun_name_ae546d_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='cities_stat_name_82543c_idx'),
        ),
    ]
