# Generated by Django 3.2.13 on 2022-06-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20220620_0518'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state'], name='cities_city_state_i_d1dd88_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='cities_city_country_0d998a_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name', 'state'], name='cities_city_name_aa5df0_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['state_code'], name='cities_stat_state_c_eeccf0_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name', 'country'], name='cities_stat_name_3ea75d_idx'),
        ),
    ]
