# Generated by Django 3.2.13 on 2022-05-05 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Email', 'Email'), ('Blog', 'Blog'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Source')),
                ('amount_of_experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount of Experience')),
                ('driver_type', models.CharField(blank=True, choices=[('Carrier', 'Carrier'), ('Owner Operator', 'Owner Operator')], max_length=50, null=True, verbose_name='Driver Type')),
                ('driver_or_carrier_to_onboard', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('number_of_dispatcher', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount of Dispatcher')),
                ('no_of_drivers', models.PositiveIntegerField(blank=True, null=True, verbose_name='No of Drivers')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
