# Generated by Django 3.2.13 on 2022-05-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatcher',
            old_name='name',
            new_name='organization_name',
        ),
    ]
