# Generated by Django 3.2.13 on 2022-05-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_dispatcherw9information'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('dirver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirver name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone no')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
