# Generated by Django 3.2.13 on 2022-05-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0005_rename_dirver_name_dispatcherreference_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcherreference',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.dispatcher'),
        ),
    ]
