# Generated by Django 3.2.13 on 2022-05-10 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0006_dispatcherreference_dispatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='dispatcherreference',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='dispatcherw9information',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
    ]
