# Generated by Django 3.2.13 on 2022-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0007_auto_20220510_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherw9information',
            name='w9_document',
            field=models.FileField(blank=True, null=True, upload_to='dispatcher/w9-information', verbose_name='W9 form and and Tax ID Number'),
        ),
    ]
