# Generated by Django 3.2.13 on 2022-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0011_dispatcherserviceagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherw9information',
            name='w9_document',
            field=models.FileField(blank=True, null=True, upload_to='dispatcher/dispatcher_w9_information', verbose_name='W9 form and and Tax ID Number'),
        ),
    ]
