# Generated by Django 3.2.13 on 2022-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0012_alter_dispatcherw9information_w9_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherserviceagreement',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
