# Generated by Django 3.2.13 on 2022-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0013_auto_20220602_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcheruser',
            name='is_current_organization',
            field=models.BooleanField(default=False, help_text='To Find the Current Dispatcher Organization'),
        ),
    ]
