# Generated by Django 3.2.13 on 2022-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0014_dispatcheruser_is_current_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='driver_type',
            field=models.CharField(blank=True, choices=[('carrier', 'Carrier'), ('owner_operator', 'Owner Operator')], max_length=50, null=True, verbose_name='Driver Type'),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='source',
            field=models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('email', 'Email'), ('blog', 'Blog'), ('other', 'Other')], max_length=50, null=True, verbose_name='Source'),
        ),
    ]
