# Generated by Django 3.2.13 on 2022-06-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0013_alter_dispatcherserviceagreement_is_signed'),
        ('dispatcher', '0017_dispatcherinvitation_active'),
    ]

    operations = [
    ]
