# Generated by Django 3.2.13 on 2022-06-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0017_dispatcherinvitation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcherinvitation',
            name='commision',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Commision of the invited dispatcher'),
        ),
    ]
