# Generated by Django 3.2.13 on 2022-06-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0020_dispatcheradmininvitation_pending_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcherinvitation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='dispatcherinvitation',
            name='commision',
        ),
        migrations.AddField(
            model_name='dispatcheruser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispatcheruser',
            name='commision',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Commision of the invited dispatcher'),
        ),
    ]
