# Generated by Django 3.2.13 on 2022-06-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0021_auto_20220610_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcheradmininvitation',
            name='pending_invitation',
        ),
        migrations.RemoveField(
            model_name='dispatcheradmininvitation',
            name='permission',
        ),
        migrations.AddField(
            model_name='dispatcheruser',
            name='pending_invitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatcheruser',
            name='permission',
            field=models.CharField(blank=True, choices=[('full_admin', 'Full Admin'), ('redy_only_admin', 'Read Only Admin')], default='redy_only_admin', max_length=20, null=True),
        ),
    ]
