# Generated by Django 3.2.13 on 2022-06-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0018_merge_20220607_1001'),
        ('dispatcher', '0023_auto_20220610_0551'),
    ]

    operations = [
    ]
