# Generated by Django 3.2.13 on 2022-06-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0024_merge_20220614_0420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DispatcherAdminInvitation',
        ),
    ]
