# Generated by Django 3.2.13 on 2022-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0026_merge_20220614_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherreference',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
