# Generated by Django 3.2.13 on 2022-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0027_alter_dispatcherreference_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dispatcher',
            index=models.Index(fields=['id'], name='dispatcher__id_fd6313_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherinvitation',
            index=models.Index(fields=['id'], name='dispatcher__id_b234df_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherinvitation',
            index=models.Index(fields=['dispatcher'], name='dispatcher__dispatc_d530e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherreference',
            index=models.Index(fields=['id'], name='dispatcher__id_2c520a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherreference',
            index=models.Index(fields=['dispatcher'], name='dispatcher__dispatc_b9f392_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherserviceagreement',
            index=models.Index(fields=['id'], name='dispatcher__id_c7ca8c_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherserviceagreement',
            index=models.Index(fields=['dispatcher'], name='dispatcher__dispatc_87b358_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcheruser',
            index=models.Index(fields=['id'], name='dispatcher__id_c15a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcheruser',
            index=models.Index(fields=['user', 'access_type'], name='dispatcher__user_id_91bded_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcheruser',
            index=models.Index(fields=['user', 'is_current_organization'], name='dispatcher__user_id_f370d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcheruser',
            index=models.Index(fields=['dispatcher', 'is_owner'], name='dispatcher__dispatc_491e33_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcheruser',
            index=models.Index(fields=['user', 'is_owner'], name='dispatcher__user_id_c64e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcheruser',
            index=models.Index(fields=['user', 'dispatcher'], name='dispatcher__user_id_9c957b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherw9information',
            index=models.Index(fields=['id'], name='dispatcher__id_f88b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatcherw9information',
            index=models.Index(fields=['dispatcher'], name='dispatcher__dispatc_cb0016_idx'),
        ),
    ]
