# Generated by Django 3.2.13 on 2022-07-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0012_carrierdriver_carrier_user'),
        ('dispatcher', '0026_merge_20220614_0919'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0013_bookloaddeliveryproof_signature'),
        ('carrier', '0024_remove_carrieruser_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(blank=True, choices=[('rate_confirmation', 'Rate Confirmation'), ('delivery_proof', 'Delivery Proof'), ('driver_response', 'Driver Response'), ('book_load', 'Book Load'), ('assign_driver_to_load', 'Assign Driver To Load')], max_length=100, null=True, verbose_name='Notification Type')),
                ('external_load_id', models.CharField(blank=True, max_length=300, null=True)),
                ('driver_response_for_load', models.BooleanField(default=False)),
                ('reason', models.TextField(max_length=1000)),
                ('is_seen', models.BooleanField(default=False)),
                ('book_load', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookload')),
                ('carrier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
                ('carrier_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser')),
                ('delivery_proof', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bookloaddeliveryproof')),
                ('dispatcher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.dispatcher')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
