# Generated by Django 3.2.13 on 2022-05-12 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrier', '0008_auto_20220511_0535'),
        ('vehicle', '0004_alter_vehicle_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('avalible', models.BooleanField(default=True)),
                ('priceVisibility', models.BooleanField(default=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='License number')),
                ('commision_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Commision percentage of driver')),
                ('automatic_calculations', models.BooleanField(default=False, verbose_name='Automatic percentage Calculations')),
                ('t_shirt_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL')], max_length=20, null=True, verbose_name='Driver t-shirt size')),
                ('is_owner_operator', models.BooleanField(default=False, verbose_name='Is Driver Owner Operator')),
                ('can_manage_load', models.BooleanField(default=False, verbose_name='Driver can Manage Load')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
