# Generated by Django 3.2.13 on 2022-05-12 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0008_auto_20220511_0535'),
        ('vehicle', '0004_alter_vehicle_uid'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='active',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='automatic_calculations',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='can_manage_load',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='commision_percentage',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_owner_operator',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='priceVisibility',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='DriverCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('priceVisibility', models.BooleanField(default=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='License number')),
                ('commision_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Commision percentage of driver')),
                ('automatic_calculations', models.BooleanField(default=False, verbose_name='Automatic percentage Calculations')),
                ('is_owner_operator', models.BooleanField(default=False, verbose_name='Is Driver Owner Operator')),
                ('can_manage_load', models.BooleanField(default=False, verbose_name='Driver can Manage Load')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
