# Generated by Django 3.2.13 on 2022-05-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0008_auto_20220511_0535'),
        ('vehicle', '0004_alter_vehicle_uid'),
        ('driver', '0002_auto_20220512_0837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverCarrier',
            new_name='CarrierDriver',
        ),
    ]
