# Generated by Django 3.2.13 on 2022-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_rename_drivercarrier_carrierdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='avalible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
