# Generated by Django 3.2.13 on 2022-05-16 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_uid'),
        ('driver', '0004_alter_driver_avalible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierdriver',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle'),
        ),
    ]
