# Generated by Django 3.2.13 on 2022-05-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_alter_carrierdriver_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='avalible',
            new_name='available',
        ),
        migrations.AddField(
            model_name='carrierdriver',
            name='is_current_carrier',
            field=models.BooleanField(default=False, verbose_name='Is current carrier'),
        ),
    ]
