# Generated by Django 3.2.13 on 2022-05-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20220516_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
