# Generated by Django 3.2.13 on 2022-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_alter_driver_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierdriver',
            name='reject_load',
            field=models.BooleanField(default=False, verbose_name='Driver can Reject load'),
        ),
    ]
