# Generated by Django 3.2.13 on 2022-05-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_carrierdriver_reject_load'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrierdriver',
            old_name='reject_load',
            new_name='can_reject_load',
        ),
    ]
