# Generated by Django 3.2.13 on 2022-05-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_rename_reject_load_carrierdriver_can_reject_load'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrierdriver',
            old_name='priceVisibility',
            new_name='price_visibility',
        ),
    ]
