# Generated by Django 3.2.13 on 2022-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_rename_pricevisibility_carrierdriver_price_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('2xl', '2XL')], max_length=20, null=True, verbose_name='Driver t-shirt size'),
        ),
    ]
