# Generated by Django 3.2.13 on 2022-06-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0023_delete_carrieradmininvitation'),
        ('driver', '0011_alter_driver_t_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierdriver',
            name='carrier_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrieruser'),
        ),
    ]
