# Generated by Django 3.2.13 on 2022-09-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_auto_20220810_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierdriver',
            name='is_current_carrier',
            field=models.BooleanField(default=True, verbose_name='Is current carrier'),
        ),
    ]
