# Generated by Django 3.2.13 on 2022-08-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_drivercurrentlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercurrentlocation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drivercurrentlocation',
            name='street',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
