# Generated by Django 3.2.13 on 2022-09-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_alter_carrierdriver_is_current_carrier'),
        ('driver', '0015_auto_20220815_1240'),
    ]

    operations = [
    ]
