# Generated by Django 3.2.13 on 2022-12-20 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0007_auto_20221219_1517'),
        ('loads', '0010_auto_20221202_1829'),
        ('carrier', '0030_auto_20221219_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='')),
                ('amount_due_in_cents', models.PositiveIntegerField()),
                ('amount_paid_in_cents', models.PositiveIntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='broker.broker')),
                ('carrier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carrier.carrieruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factored', models.BooleanField()),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loads.load')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount_in_cents', models.PositiveIntegerField()),
                ('fee_amount_in_cents', models.PositiveIntegerField()),
                ('lender', models.CharField(blank=True, choices=[('oatfi', 'OATFI')], default='', max_length=50)),
                ('lender_loan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('offered', 'OFFERED'), ('outstanding', 'OUTSTANDING'), ('closed', 'CLOSED'), ('late', 'LATE'), ('default', 'DEFAULT')], default='', max_length=50)),
                ('terms', models.TextField()),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_timestamp', models.DateTimeField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_in_cents', models.PositiveIntegerField()),
                ('stripe_ref_id', models.CharField(max_length=300)),
                ('payment_type', models.CharField(choices=[('to_carrier', 'TO_CARRIER'), ('from_broker', 'FROM_BROKER'), ('fee', 'FEE'), ('loan_repayment', 'LOAN_REPAYMENT'), ('loan_payout', 'LOAN_PAYOUT')], max_length=30)),
                ('load_settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.loadsettlement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.loan')),
            ],
            options={
                'db_table': 'loan_status_history',
            },
        ),
        migrations.CreateModel(
            name='LoadSettlementStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('load_settlement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.loadsettlement')),
            ],
            options={
                'db_table': 'load_settlement_status_history',
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.invoice')),
            ],
            options={
                'db_table': 'invoice_status_history',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='load_settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.loadsettlement'),
        ),
    ]
