# Generated by Django 3.2.13 on 2022-12-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsettlement',
            name='nauvus_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='loadsettlement',
            name='nauvus_fees_in_cents',
            field=models.IntegerField(default=0),
        ),
    ]
