# Generated by Django 3.2.13 on 2022-12-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20221229_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadsettlement',
            name='factored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='terms_accepted_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
