# Generated by Django 3.2.13 on 2022-12-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20221230_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadsettlement',
            name='factored',
        ),
    ]
