# Generated by Django 3.2.13 on 2022-12-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_loadsettlement_factored'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsettlement',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadsettlement',
            name='terms_accepted_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='load_settlement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.loadsettlement'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.invoice'),
        ),
    ]
