# Generated by Django 3.2.13 on 2023-01-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20230102_2016'),
        ('payments', '0005_auto_20221231_1357'),
    ]

    operations = [
    ]
