# Generated by Django 3.2.13 on 2023-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_merge_0003_auto_20230102_2016_0005_auto_20221231_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, default='unpaid', max_length=255, null=True),
        ),
    ]
