# Generated by Django 3.2.13 on 2022-08-03 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee_email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('invitation_type', models.CharField(blank=True, choices=[('carrier_admin_to_carrier_admin', 'Carrier Admin To Carrier Admin'), ('carrier_admin_to_carrier_user', 'Carrier Admin To Carrier User'), ('carrier_admin_to_driver', 'Carrier Admin To Driver'), ('carrier_admin_to_dispatcher', 'Carrier Admin To Dispatcher'), ('dispatcher_admin_to_dispatcher_admin', 'Dispatcher Admin To Dispatcher Admin'), ('dispatcher_admin_to_dispatcher_user', 'Dispatcher Admin To Dispatcher User'), ('dispatcher_admin_to_carrier', 'Dispatcher Admin To Carrier')], max_length=200, null=True, verbose_name='Invitation Type')),
                ('status', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=200, null=True, verbose_name='Status Type')),
                ('first_name', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=200, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=200, null=True, verbose_name='Last Name')),
                ('access_type', models.CharField(blank=True, choices=[('full_admin', 'Full Admin'), ('redy_only_admin', 'Read Only Admin')], default='redy_only_admin', max_length=20, null=True)),
                ('invitee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
