# Generated by Django 3.2.13 on 2022-08-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0027_alter_dispatcherreference_email'),
        ('carrier', '0025_auto_20220705_0516'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='carrier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='dispatcher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.dispatcher'),
        ),
    ]
