# Generated by Django 3.2.13 on 2022-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20220803_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitee_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
