# Generated by Django 3.2.13 on 2022-11-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitation_invitee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='dispatcher',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitation_type',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_role',
            field=models.CharField(blank=True, choices=[('driver', 'driver'), ('dispatcher', 'dispatcher'), ('secondary_user', 'secondary_user')], max_length=200, null=True, verbose_name='Invitation Type'),
        ),
    ]
