# Generated by Django 3.2.13 on 2022-11-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_auto_20221110_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invitation_role',
            new_name='invitation_type',
        ),
    ]
