# Generated by Django 3.2.13 on 2022-07-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadPayment',
        ),
    ]
