# Generated by Django 3.2.13 on 2022-07-20 04:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0012_carrierdriver_carrier_user'),
        ('dispatcher', '0027_alter_dispatcherreference_email'),
        ('carrier', '0025_auto_20220705_0516'),
        ('bookings', '0016_auto_20220720_0447'),
        ('banking', '0002_delete_loadpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nauvus_percentage', models.FloatField(verbose_name='Nauvus percentage from load price.')),
                ('nauvus_price', models.FloatField(blank=True, null=True)),
                ('carrier_percentage', models.FloatField(blank=True, null=True, verbose_name='Carrier percentage from load price.')),
                ('carrier_price', models.FloatField(blank=True, null=True)),
                ('dispatcher_percentage', models.FloatField(blank=True, null=True, verbose_name='Disapatcher percentage from load price')),
                ('dispatcher_price', models.FloatField(blank=True, null=True)),
                ('driver_percentage', models.FloatField(blank=True, null=True, verbose_name='Driver percentage from load price.')),
                ('driver_price', models.FloatField(blank=True, null=True)),
                ('book_load_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookload')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carrier.carrier')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher.dispatcher')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='driver.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
