# Generated by Django 3.2.13 on 2022-07-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_remove_bookload_is_booked_by_dispatcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0005_loadpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('transfer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payout_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payout', models.BooleanField(default=False)),
                ('receive', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default={})),
                ('book_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
